### PR TITLE
Fixes #800: cannot iterate over class array

### LINKED ISSUE #800: Cannot iterate (must implement...) on @phpdoc class[]
Problem is similar to "Incorrect inspection error with foreach over iterable  #793" but I'm not sure it same

```
namespace B;
// any class. doesn't reproduce with scalars
/**
 * @param \stdClass[] $array
 */
function aaa(array $array)
{
   //  array_reverse got false positive error 
    foreach (array_reverse($array) as $item) {
        $item->a();
    }
}
```
phpstorm

### PR DESCRIPTION
**Pull request by rentalhost**
* 1d2ff48: bugfix;
  * Actually it was just a simple `if()` for negate the `types.contains(Types.strArray)`;
* 2b57488: updated the code-style;
  * L155: Fixed non-null argument;
  * `String.replace()` was changed to `String.format()`;

### CODE REVIEW

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java [hunk 1]
```diff
@@ -92,60 +113,76 @@ private boolean isEnsuredByPyParentIf(@NotNull ForeachStatement foreach, @NotNul
...
                     }
+
                     return;
                 }
 
                 /* false-positives: multiple return types checked only in function/method; no global context */
                 final PsiElement scope = ExpressionSemanticUtil.getBlockScope(container);
-                if (types.size() > 1 && !(scope instanceof Function)) {
+
+                if ((types.size() > 1) && !(scope instanceof Function)) {
```
Comment (kalessil) [inline src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: Where the extra line + extra `()` are coming from? 
It would make my reviewer life easier to get the original code style back =)

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java [hunk 2]
```diff
@@ -92,60 +113,76 @@ private boolean isEnsuredByPyParentIf(@NotNull ForeachStatement foreach, @NotNul
                 return result;
             }
 
-            private void analyseContainer(@NotNull PsiElement container) {
+            private void analyseContainer(@NotNull final PsiElement container) {
```
Comment (kalessil) [inline src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: Parameters don't need to be final, only if has a purpose (but local variables are final for sure).

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java [hunk 3]
```diff
@@ -54,33 +73,35 @@ public String getShortName() {
...
-                    if (ifCandidate instanceof If) {
-                        conditions = ((If) ifCandidate).getCondition();
-                    } else if (ifCandidate instanceof ElseIf) {
-                        conditions = ((ElseIf) ifCandidate).getCondition();
-                    } else {
-                        conditions = null;
+                    final PsiElement ifCandidate = (foreach.getParent() instanceof GroupStatement) ? foreach.getParent().getParent() : null;
+                    PsiElement       conditions  = null;
+
+                    if (ifCandidate instanceof ControlStatement) {
```
Comment (kalessil) [inline src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: Catches lots of other constructs (not only If, ElseIf) - is it intended?

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java [hunk 4]
```diff
@@ -35,15 +54,15 @@
  */
 
 public class ForeachSourceInspector extends BasePhpInspection {
+    private static final String patternNotRecognized = "Expressions' type was not recognized, please check type hints.";
+    private static final String patternMixedTypes    = "Expressions' type contains '%s', please specify possible types instead (best practices).";
+    private static final String patternScalar        = "Can not iterate '%s' (re-check type hints).";
+    private static final String patternObject        = "Can not iterate '%s' (must implement one of Iterator interfaces).";
+
```
Comment (kalessil) [inline src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: +1, thank you =)

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java (hunk 1 above)
Comment (rentalhost) [reply src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: By topics:

1. The extra line is just to make clear the `if()` vs variable initialization. The code is more "spaced" and it turn the readability better in "long term usage".
2. The extra `()` is IDE thing actually. I enabled a lot of Java inspections on past and one of them is something like "unclear expression". It requires that we add an extra `()` in complex conditionals to delimit each part of expression. It is useful in sometimes, but cases like that I don't think that is very useful, but I too don't care about that. But I can undo that if you prefer. Maybe disable this inspection for you project.
3. Oh. Don't care too much with "update code-style" commits, once that it don't modify the code (except if I describe it - actually I merged the `String.format()` part with this commit accidentally, because the idea is that this commit fix only the style and not modify behavior). It is basically to make code readability better and solve all IDE inspections.

Anyway, if you don't like it I could make a new PR with only the real fix.

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java (hunk 2 above)
Comment (rentalhost) [reply src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: While it really is not need, I think that is valid to make sure that this parameter is never modified.

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java (hunk 3 above)
Comment (rentalhost) [reply src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: It will catch some additional constructs, really. But will support things like that:

```php
switch (true){
    case is_array($value):
        foreach ($value as $item) {
        }
        break;
}
```

And too to `while()`, `do while()` and `for()` conditionals. But we can limit to works strictly with that types, once that it will includes `catch()` and `finally()` that don't have really a conditional.

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java (hunk 1 above)
Comment (kalessil) [reply src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: Yes, please (keep the fix and String.format changes only) =)

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java (hunk 2 above)
Comment (kalessil) [reply src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: No need ATM

File: src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java (hunk 3 above)
Comment (kalessil) [reply src/main/java/com/kalessil/phpStorm/phpInspectionsEA/inspectors/forEach/ForeachSourceInspector.java]: Let's stick to If, ElseIf - I'd like to minimize this inspection modification - it's very problematic one =_

**Comment by rentalhost** [comment]
I'll back to work on this fix on this weekend.

**Comment by kalessil** [comment]
@rentalhost I made changes in master, leading to conflict. Sorry.

**Comment by rentalhost** [comment]
@kalessil No problem! I will rework on this source to make this PR clean.

**Comment by rentalhost** [comment]
Okay, I have reduced all modifications to fixes the `String.replace()` to `String.format()`, converting to regular comparison style where was Yoda style and the fix itself. But Github shows all changes related to space things, so the changes history still is confuses, but less than before. :smile: 

In anyway, I think that this inspection should be rewrite in some moment, once that it is very confuses and seems few optimized. The `analyseContainer()` method for instance is very long and confuses. I don't, for instance, if I can move the fix to top (it don't break any test, but I think that is not a good thing at this time).

**Comment by kalessil** [comment]
Looks good, I'll merge today.

**Comment by kalessil** [comment]
Thank you @rentalhost
